site_name: SQL-operator
repo_url: https://github.com/stenic/sql-operator
strict: true
theme:
  name: material
  icon:
    logo: material/database-cog
  palette:
    primary: blue
  font:
    text: Work Sans
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - core-concepts.md
  - getting-started.md
  - crds.md
  - Extras:
    - extras/argocd.md